language: java

# This (sudo: false) is needed to "run on container-based infrastructure" on
# which cache: is available
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/caching/#Arbitrary-directories
cache:
  directories:
  - $HOME/.m2

addons:
  apt_packages:
    - git

jdk:
  - oraclejdk8
  - openjdk7

env:
  - BUILD=maven

matrix:
  fast_finish: true

before_install:
  - pip install --user flake8 Sphinx

script:
  - ./tools/test-build $BUILD
