language: java

# This (sudo: false) is needed to "run on container-based infrastructure" on
# which cache: is available
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/caching/#Arbitrary-directories
cache:
  directories:
  - $HOME/.m2
  - downloads

addons:
  apt_packages:
    - git

jdk:
  - oraclejdk9
  - oraclejdk8
  - openjdk7

env:
  - BUILD=maven
  - BUILD=ant

matrix:
  fast_finish: true

before_install:
  - if [[ $BUILD == 'ant' ]]; then pip install --user flake8 Sphinx; fi
  - mkdir -p downloads
  - if [[ ! -f downloads/maven.tar.gz ]]; then curl -o downloads/maven.tar.gz http://mirror.ox.ac.uk/sites/rsync.apache.org/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz; fi
  - tar xf downloads/maven.tar.gz
  - export PATH=$(pwd)/apache-maven-3.5.0/bin:$PATH

script:
  - ./tools/test-build $BUILD
